### PR TITLE
Post comment thread

### PR DESCRIPTION
**Pull request by Mingye1Li**
# Changelogs

### Basic sorting and filtering for posts listed in the **active thread** tab
   - filter posts by created time (All Time/ Latest 3 Days)
   - filter posts by post categories
   - sort by post created time
   - sort by number of comments
   - sort by number of upvote/downvote 
   - sort ordering asc/desc
### Active thread page
- Load more post from main database when you scroll to the bottom
- Only show comments count on the post card from the **active thread** page
- route to the seperated post page when you click comments on the post card
### Move comments for the same post to a seperated page
(e.g. comments for post with postId:12 will be demo.ourvoice.test/posts/12)
- create comment for post and reply for comment from the seperated post page
### Basic vote functionality for post and comment 
- vote for a specific post/comment from each user can only be 'no vote'/'up vote' /'down vote'

### API for vote 
- basic CRUD methods for vote
- vote create/delete operation  will be directly sent to the main database
### API for comment
- comment creation operation will be sent to the premoderation database first

## Todos 
- Implement load more comments in the seperated post page
- Unit test for vote api
- E2E test for filtering and sorting post on the active thread page
- E2E test for create comment from the seperated post page

### CODE REVIEW

**Comment by cheburan** [comment]
Hi @Mingye1Li ! Can you please merge the latest changes from the dev and check the conflicts? I assume it will also help with the failing CI too

**Comment by Mingye1Li** [comment]
Hi Dinislam,

Apologize for the late reply.
Sure, I'll spend some time to look into it.

**Comment by cheburan** [comment]
> `apps/ourvoice-api/src/modules/moderation/comment-moderation/comment-moderation.repository.ts`
> `apps/ourvoice-api/src/modules/moderation/scheduled-moderation-service.ts`
> `apps/ourvoice-api/src/modules/post/post.resolver.ts`
> `apps/ourvoice-app/package.json`
> `pnpm-lock.yaml`

No worries. Can you please have a look at the conflicts too? @Mingye1Li

**Comment by Mingye1Li** [comment]
Sure, I will check it.

**Pull request merged**
